AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  An Amazon S3 trigger that retrieves metadata for the object that has been
  updated.
Parameters:
  BucketName:
    Description: S3 Bucket name
    Type: String
    Default: ktsr42.s3.heating
  LambdaRoleName:
    Description: Name for the IAM role assigned to the lambda
    Type: String
    Default: ktsr42.lambda_role.heating
  PublishingUserName:
    Description: Name for the IAM user that will be publishing readings to the S3 bucket
    Type: String
    Default: ktsr42heatingPublisher
Resources:
  bucket:
    Type: AWS::S3::Bucket
    DependsOn: BucketPermission
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: 's3:ObjectCreated:*'
          Filter:
            S3Key:
              Rules:
                - Name: prefix
                  Value: observations
          Function: !GetAtt BucketWatcher.Arn
  BucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref BucketWatcher
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Sub "arn:aws:s3:::${BucketName}"
  BucketWatcher:
    Type: AWS::Lambda::Function
    Properties:
      Description: Sends a Wait Condition signal to Handle when invoked
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: "ktsr42_lambda_test2"
      Runtime: python3.6
      Code:
        S3Bucket: ktsr42.s3.code
        S3Key: code/nx.zip
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          CONFIG_BUCKET: !Ref BucketName
  StatusCheckEvent:
    Type: AWS::Events::Rule
    Properties:
      Name: ktsr42.event.heating_check
      ScheduleExpression: rate(4 hours)
      Targets:
        -
          Arn:
            !GetAtt BucketWatcher.Arn
          Id: HeatingScheduledEvent
  StatusCheckPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BucketWatcher
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StatusCheckEvent.Arn
  PublishingUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref PublishingUserName
      Policies:
      - PolicyName: S3PublishingPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:PutObject'
              Resource: "arn:aws:s3:::*"      
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {Service: [lambda.amazonaws.com]}
          Action: ['sts:AssumeRole']
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
      - PolicyName: S3Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
              Resource: "arn:aws:s3:::*"
      - PolicyName: SNSPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sns:Publish'
              Resource: "*"
